import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Web3Provider } from "./Web3Provider";
import { Toaster } from "sonner"; 

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});
const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className="bg-gradient-to-br from-[#0F172A] via-[#1E293B] to-[#0891B2] bg-[length:400%_400%] animate-gradient-slow"
      >
        {/* Web3Provider for wagmi and react-query context */}
        <Web3Provider>
          <Toaster richColors position="top-center" /> 
          {children}
        </Web3Provider>
      </body>
    </html>
  );
}
